### ISSUE TITLE
error running chapter02.EntreeDatasetPipeline

### ISSUE THREAD

**Issue by minodeangelis** [tuxdna/BuildingScalaRecommendationEngine#3]
Hello,
I'm trying to run the EntreeDatasetPipeline. I didn't change anything in build.sbt 
I installed a vbox with:

```
ubuntu 14.04
mongodb 2.6.3
spark 1.4.0-hadoop2.6 with scala 2.10.4
kafka_2.10-0.8.2.0
 ```
The first examples and chapter02.Stats works fine.
The chapter02.EntreeDatasetPipeline stop with this output.
Thanks for you support.

```
mino@mino-VirtualBox ~/Documenti/BuildingRecommendationEngineWithScala $ sbt 'run-main chapter02.EntreeDatasetPipeline /home/mino/Documenti/BuildingRecommendationEngineWithScala/datasets/entree/'
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'she
ll'
[info] Loading project definition from /home/mino/Documenti/BuildingRecommendati
onEngineWithScala/project
[info] Set current project to BuildingScalaRecommendationEngine (in build file:/
home/mino/Documenti/BuildingRecommendationEngineWithScala/)
[info] Running chapter02.EntreeDatasetPipeline /home/mino/Documenti/BuildingReco
mmendationEngineWithScala/datasets/entree/
log4j:WARN No appenders could be found for logger (org.mongodb.driver.cluster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more in
fo.
[error] (run-main-0) java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at com.mongodb.casbah.BaseImports$class.$init$(Implicits.scala:162)
	at com.mongodb.casbah.Imports$.<init>(Implicits.scala:142)
	at com.mongodb.casbah.Imports$.<clinit>(Implicits.scala)
	at com.mongodb.casbah.MongoClient.apply(MongoClient.scala:219)
	at chapter02.Database$.getCollection(EntreeDatasetPipeline.scala:71)
	at chapter02.Database$.restaurantCollection$lzycompute(EntreeDatasetPipe
line.scala:75)
	at chapter02.Database$.restaurantCollection(EntreeDatasetPipeline.scala:
75)
	at chapter02.Database$.deleteAll(EntreeDatasetPipeline.scala:79)
	at chapter02.EntreeDatasetPipeline$.main(EntreeDatasetPipeline.scala:225
)
	at chapter02.EntreeDatasetPipeline.main(EntreeDatasetPipeline.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
Caused by: java.lang.IllegalArgumentException: state should be: w >= 0
	at com.mongodb.assertions.Assertions.isTrueArgument(Assertions.java:99)
	at com.mongodb.WriteConcern.<init>(WriteConcern.java:253)
	at com.mongodb.WriteConcern.<init>(WriteConcern.java:231)
	at com.mongodb.WriteConcern.<init>(WriteConcern.java:182)
	at com.mongodb.casbah.WriteConcern$.<init>(WriteConcern.scala:41)
	at com.mongodb.casbah.WriteConcern$.<clinit>(WriteConcern.scala)
	at com.mongodb.casbah.BaseImports$class.$init$(Implicits.scala:162)
	at com.mongodb.casbah.Imports$.<init>(Implicits.scala:142)
	at com.mongodb.casbah.Imports$.<clinit>(Implicits.scala)
	at com.mongodb.casbah.MongoClient.apply(MongoClient.scala:219)
	at chapter02.Database$.getCollection(EntreeDatasetPipeline.scala:71)
	at chapter02.Database$.restaurantCollection$lzycompute(EntreeDatasetPipe
line.scala:75)
	at chapter02.Database$.restaurantCollection(EntreeDatasetPipeline.scala:
75)
	at chapter02.Database$.deleteAll(EntreeDatasetPipeline.scala:79)
	at chapter02.EntreeDatasetPipeline$.main(EntreeDatasetPipeline.scala:225
)
	at chapter02.EntreeDatasetPipeline.main(EntreeDatasetPipeline.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
```

**Comment by tuxdna** [comment]
@mdeang Yes, I can reproduce the issue:

Starting Kafka

```
[kafka_2.10-0.8.2.0]$ bin/zookeeper-server-start.sh config/zookeeper.properties 
[kafka_2.10-0.8.2.0]$ bin/kafka-server-start.sh config/server.properties
```

Then starting the target program:

```
$ sbt/sbt 'run-main chapter02.EntreeDatasetPipeline /tmp/BuildingScalaRecommendationEngine/datasets/entree/'
...
log4j:WARN No appenders could be found for logger (org.mongodb.driver.cluster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[error] (run-main-0) java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at com.mongodb.casbah.BaseImports$class.$init$(Implicits.scala:162)
	at com.mongodb.casbah.Imports$.<init>(Implicits.scala:142)
	at com.mongodb.casbah.Imports$.<clinit>(Implicits.scala)
	at com.mongodb.casbah.MongoClient.apply(MongoClient.scala:219)
	at chapter02.Database$.getCollection(EntreeDatasetPipeline.scala:71)
	at chapter02.Database$.restaurantCollection$lzycompute(EntreeDatasetPipeline.scala:75)
	at chapter02.Database$.restaurantCollection(EntreeDatasetPipeline.scala:75)
	at chapter02.Database$.deleteAll(EntreeDatasetPipeline.scala:79)
	at chapter02.EntreeDatasetPipeline$.main(EntreeDatasetPipeline.scala:225)
	at chapter02.EntreeDatasetPipeline.main(EntreeDatasetPipeline.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.IllegalArgumentException: state should be: w >= 0
	at com.mongodb.assertions.Assertions.isTrueArgument(Assertions.java:99)
	at com.mongodb.WriteConcern.<init>(WriteConcern.java:253)
	at com.mongodb.WriteConcern.<init>(WriteConcern.java:231)
	at com.mongodb.WriteConcern.<init>(WriteConcern.java:182)
	at com.mongodb.casbah.WriteConcern$.<init>(WriteConcern.scala:41)
	at com.mongodb.casbah.WriteConcern$.<clinit>(WriteConcern.scala)
	at com.mongodb.casbah.BaseImports$class.$init$(Implicits.scala:162)
	at com.mongodb.casbah.Imports$.<init>(Implicits.scala:142)
	at com.mongodb.casbah.Imports$.<clinit>(Implicits.scala)
	at com.mongodb.casbah.MongoClient.apply(MongoClient.scala:219)
	at chapter02.Database$.getCollection(EntreeDatasetPipeline.scala:71)
	at chapter02.Database$.restaurantCollection$lzycompute(EntreeDatasetPipeline.scala:75)
	at chapter02.Database$.restaurantCollection(EntreeDatasetPipeline.scala:75)
	at chapter02.Database$.deleteAll(EntreeDatasetPipeline.scala:79)
	at chapter02.EntreeDatasetPipeline$.main(EntreeDatasetPipeline.scala:225)
	at chapter02.EntreeDatasetPipeline.main(EntreeDatasetPipeline.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:runMain for the full output.


```

This seems like something to do with MongoDB Scala bindings ( Casbah ).

**Comment by tuxdna** [comment]
Perhaps a dependency issue as mentioned in this post
 *[java.lang.IllegalArgumentException: state should be: w >= 0]( https://groups.google.com/forum/#!topic/mongodb-casbah-users/sDqiwvqLg8M)
